settings:
  name: "Cloud Volumes Service for AWS documentation"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Volumes Service for AWS docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Volumes Service for AWS
          url: /concept-cvs-aws.html
    - title: Use Cloud Volumes Service for AWS
      entries:
        - title: Deploy and manage cloud volumes
          url: /task-manage-cvs-aws.html
        - title: Manage cloud volumes snapshots
          url: /task-manage-cloud-volumes-snapshots.html
    - title: Concepts
      entries:
        - title: Service levels and allocated capacity
          url: /reference-cvs-service-levels-and-quotas.html
        - title: AWS security group settings for Windows AD servers
          url: /reference-security-groups-windows-ad-servers.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: tile name
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events      
